//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticWonderland.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlasticWonderland.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AppBarHome {
            get {
                return ResourceManager.GetString("AppBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string AppBarUpload {
            get {
                return ResourceManager.GetString("AppBarUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudWaveX.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is not valid for the requested usage. This error is also returned if the certificate has an invalid name..
        /// </summary>
        public static string Certificate_Error_CNMissmatch {
            get {
                return ResourceManager.GetString("Certificate_Error_CNMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file..
        /// </summary>
        public static string Certificate_Error_Expired {
            get {
                return ResourceManager.GetString("Certificate_Error_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied certificate is invalid. This can be returned for a number of reasons: A certificate that can only be used as an end-entity is being used as a CA or vice versa. A path length constraint in the certification chain has been violated. A certificate contains an unknown extension that is marked critical. A certificate is being used for a purpose other than the ones specified by its CA. A parent of a given certificate in fact did not issue that child certificate. A certificate is missing or has an emp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Certificate_Error_Invalid {
            get {
                return ResourceManager.GetString("Certificate_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate was explicitly revoked by its issuer..
        /// </summary>
        public static string Certificate_Error_Revoked {
            get {
                return ResourceManager.GetString("Certificate_Error_Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate error !.
        /// </summary>
        public static string Certificate_Error_Title {
            get {
                return ResourceManager.GetString("Certificate_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider..
        /// </summary>
        public static string Certificate_Error_UntrustedRoot {
            get {
                return ResourceManager.GetString("Certificate_Error_UntrustedRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContentLibrary_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContentLibrary_ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ContentLibrary_ContextMenu_Detail {
            get {
                return ResourceManager.GetString("ContentLibrary_ContextMenu_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading content. Please activate log and send me the error..
        /// </summary>
        public static string ContentLibrary_Error_Content_Content {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Content_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ContentLibrary_Error_Content_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while deleting the file..
        /// </summary>
        public static string ContentLibrary_Error_Delete_Content {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ContentLibrary_Error_Delete_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading the file details..
        /// </summary>
        public static string ContentLibrary_Error_Detail_Content {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Detail_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ContentLibrary_Error_Detail_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during the upload. Please try again..
        /// </summary>
        public static string ContentLibrary_Error_Upload_Content {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Upload_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ContentLibrary_Error_Upload_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_Upload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only read in this library..
        /// </summary>
        public static string ContentLibrary_Error_UploadForbidden_Content {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_UploadForbidden_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ContentLibrary_Error_UploadForbidden_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_Error_UploadForbidden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , last update .
        /// </summary>
        public static string ContentLibrary_Itemtemplate_LastUpdate {
            get {
                return ResourceManager.GetString("ContentLibrary_Itemtemplate_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : .
        /// </summary>
        public static string ContentLibrary_MessagePrompt_Detail_1 {
            get {
                return ResourceManager.GetString("ContentLibrary_MessagePrompt_Detail_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size : .
        /// </summary>
        public static string ContentLibrary_MessagePrompt_Detail_2 {
            get {
                return ResourceManager.GetString("ContentLibrary_MessagePrompt_Detail_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification : .
        /// </summary>
        public static string ContentLibrary_MessagePrompt_Detail_3 {
            get {
                return ResourceManager.GetString("ContentLibrary_MessagePrompt_Detail_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ContentLibrary_MessagePrompt_Detail_Title {
            get {
                return ResourceManager.GetString("ContentLibrary_MessagePrompt_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string ContentLibrary_PivotTitle_1 {
            get {
                return ResourceManager.GetString("ContentLibrary_PivotTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ContentLibrary_PivotTitle_2 {
            get {
                return ResourceManager.GetString("ContentLibrary_PivotTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully !.
        /// </summary>
        public static string ContentLibrary_Refresh_1 {
            get {
                return ResourceManager.GetString("ContentLibrary_Refresh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload canceled.
        /// </summary>
        public static string ContentLibrary_Upload_UploadCancel {
            get {
                return ResourceManager.GetString("ContentLibrary_Upload_UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string ContentLibrary_Upload_UploadingWaiting {
            get {
                return ResourceManager.GetString("ContentLibrary_Upload_UploadingWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success !.
        /// </summary>
        public static string ContentLibrary_Upload_UploadOK {
            get {
                return ResourceManager.GetString("ContentLibrary_Upload_UploadOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Download_Button_Cancel {
            get {
                return ResourceManager.GetString("Download_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Download_Button_Open {
            get {
                return ResourceManager.GetString("Download_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while downloading the file. Please try again..
        /// </summary>
        public static string Download_Error_Download_Content {
            get {
                return ResourceManager.GetString("Download_Error_Download_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string Download_Error_Download_Title {
            get {
                return ResourceManager.GetString("Download_Error_Download_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue with the filename. If the name start with a special character, please delete the cache and try again..
        /// </summary>
        public static string Download_Error_StoreFile_Content_1 {
            get {
                return ResourceManager.GetString("Download_Error_StoreFile_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while downloading..
        /// </summary>
        public static string Download_Error_StoreFile_Content_2 {
            get {
                return ResourceManager.GetString("Download_Error_StoreFile_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded .
        /// </summary>
        public static string Download_Result_Text_1 {
            get {
                return ResourceManager.GetString("Download_Result_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  / .
        /// </summary>
        public static string Download_Result_Text_2 {
            get {
                return ResourceManager.GetString("Download_Result_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kbytes, .
        /// </summary>
        public static string Download_Result_Text_3 {
            get {
                return ResourceManager.GetString("Download_Result_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  % completed. .
        /// </summary>
        public static string Download_Result_Text_4 {
            get {
                return ResourceManager.GetString("Download_Result_Text_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download result.
        /// </summary>
        public static string Download_Result_Text_Title {
            get {
                return ResourceManager.GetString("Download_Result_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading : .
        /// </summary>
        public static string Download_Status_Text_1 {
            get {
                return ResourceManager.GetString("Download_Status_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... Please wait .
        /// </summary>
        public static string Download_Status_Text_2 {
            get {
                return ResourceManager.GetString("Download_Status_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled..
        /// </summary>
        public static string Download_Status_Text_3 {
            get {
                return ResourceManager.GetString("Download_Status_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error..
        /// </summary>
        public static string Download_Status_Text_4 {
            get {
                return ResourceManager.GetString("Download_Status_Text_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed !.
        /// </summary>
        public static string Download_Status_Text_5 {
            get {
                return ResourceManager.GetString("Download_Status_Text_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download status.
        /// </summary>
        public static string Download_Status_Text_Title {
            get {
                return ResourceManager.GetString("Download_Status_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        public static string Download_Title_1 {
            get {
                return ResourceManager.GetString("Download_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently using .
        /// </summary>
        public static string ListLibrary_Account_1 {
            get {
                return ResourceManager.GetString("ListLibrary_Account_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on your account. This value represents .
        /// </summary>
        public static string ListLibrary_Account_2 {
            get {
                return ResourceManager.GetString("ListLibrary_Account_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of your quota..
        /// </summary>
        public static string ListLibrary_Account_3 {
            get {
                return ResourceManager.GetString("ListLibrary_Account_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on your account..
        /// </summary>
        public static string ListLibrary_Account_4 {
            get {
                return ResourceManager.GetString("ListLibrary_Account_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota status :.
        /// </summary>
        public static string ListLibrary_AccountInfosQuotaStatus {
            get {
                return ResourceManager.GetString("ListLibrary_AccountInfosQuotaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage :.
        /// </summary>
        public static string ListLibrary_AccountInfosUsage {
            get {
                return ResourceManager.GetString("ListLibrary_AccountInfosUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while getting user information data..
        /// </summary>
        public static string ListLibrary_Error_AccountInfos {
            get {
                return ResourceManager.GetString("ListLibrary_Error_AccountInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading libraries. Please activate log and send me the error..
        /// </summary>
        public static string ListLibrary_Error_ListLibrary_Content {
            get {
                return ResourceManager.GetString("ListLibrary_Error_ListLibrary_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ListLibrary_Error_ListLibrary_Title {
            get {
                return ResourceManager.GetString("ListLibrary_Error_ListLibrary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be in a library to upload..
        /// </summary>
        public static string ListLibrary_Error_NoUpload_Content {
            get {
                return ResourceManager.GetString("ListLibrary_Error_NoUpload_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ListLibrary_Error_NoUpload_Title {
            get {
                return ResourceManager.GetString("ListLibrary_Error_NoUpload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library password is wrong. .
        /// </summary>
        public static string ListLibrary_LibCrypt_Error_Content {
            get {
                return ResourceManager.GetString("ListLibrary_LibCrypt_Error_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string ListLibrary_LibCrypt_Error_Title {
            get {
                return ResourceManager.GetString("ListLibrary_LibCrypt_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the library password.
        /// </summary>
        public static string ListLibrary_LibCrypt_PasswordInput_Message {
            get {
                return ResourceManager.GetString("ListLibrary_LibCrypt_PasswordInput_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library password.
        /// </summary>
        public static string ListLibrary_LibCrypt_PasswordInput_Title {
            get {
                return ResourceManager.GetString("ListLibrary_LibCrypt_PasswordInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current usage in %.
        /// </summary>
        public static string ListLibrary_Pie_Title_1 {
            get {
                return ResourceManager.GetString("ListLibrary_Pie_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaning space in %.
        /// </summary>
        public static string ListLibrary_Pie_Title_2 {
            get {
                return ResourceManager.GetString("ListLibrary_Pie_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current usage in %.
        /// </summary>
        public static string ListLibrary_Pie_Title_3 {
            get {
                return ResourceManager.GetString("ListLibrary_Pie_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All libraries.
        /// </summary>
        public static string ListLibrary_PivotTitle_1 {
            get {
                return ResourceManager.GetString("ListLibrary_PivotTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ListLibrary_PivotTitle_2 {
            get {
                return ResourceManager.GetString("ListLibrary_PivotTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ListLibrary_PivotTitle_3 {
            get {
                return ResourceManager.GetString("ListLibrary_PivotTitle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your account, quota are disabled..
        /// </summary>
        public static string ListLibrary_Quota_Status_Disabled {
            get {
                return ResourceManager.GetString("ListLibrary_Quota_Status_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your account, quota are enabled..
        /// </summary>
        public static string ListLibrary_Quota_Status_Enabled {
            get {
                return ResourceManager.GetString("ListLibrary_Quota_Status_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Login_AccountName {
            get {
                return ResourceManager.GetString("Login_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL and port.
        /// </summary>
        public static string Login_Address {
            get {
                return ResourceManager.GetString("Login_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        public static string Login_Address_Content {
            get {
                return ResourceManager.GetString("Login_Address_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Self-Signed Certificate.
        /// </summary>
        public static string Login_Checkbox_IgnoreSelfSigned {
            get {
                return ResourceManager.GetString("Login_Checkbox_IgnoreSelfSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Login_CheckBox_RemberMe {
            get {
                return ResourceManager.GetString("Login_CheckBox_RemberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have Internet access to use the app..
        /// </summary>
        public static string Login_Error_NoInternet_Content {
            get {
                return ResourceManager.GetString("Login_Error_NoInternet_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string Login_Error_NoInternet_Title {
            get {
                return ResourceManager.GetString("Login_Error_NoInternet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must correct the SSL certificate or accept the warning..
        /// </summary>
        public static string Login_Error_SSL_NotValidate_Content {
            get {
                return ResourceManager.GetString("Login_Error_SSL_NotValidate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string Login_Error_SSL_NotValidate_Title {
            get {
                return ResourceManager.GetString("Login_Error_SSL_NotValidate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is not valid..
        /// </summary>
        public static string Login_Error_URL_NotValid_Content {
            get {
                return ResourceManager.GetString("Login_Error_URL_NotValid_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string Login_Error_URL_NotValid_Title {
            get {
                return ResourceManager.GetString("Login_Error_URL_NotValid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password wrong.
        /// </summary>
        public static string Login_Error_WrongUser_Content {
            get {
                return ResourceManager.GetString("Login_Error_WrongUser_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error !.
        /// </summary>
        public static string Login_Error_WrongUser_Title {
            get {
                return ResourceManager.GetString("Login_Error_WrongUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_PivotTitle_1 {
            get {
                return ResourceManager.GetString("Login_PivotTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Login_PivotTitle_2 {
            get {
                return ResourceManager.GetString("Login_PivotTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send log.
        /// </summary>
        public static string PivotHelpControl_Button {
            get {
                return ResourceManager.GetString("PivotHelpControl_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PivotHelpControl_Off {
            get {
                return ResourceManager.GetString("PivotHelpControl_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PivotHelpControl_On {
            get {
                return ResourceManager.GetString("PivotHelpControl_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are having trouble with this app, you can use the switch below to record information about how you use the app to send back to me..
        /// </summary>
        public static string PivotHelpControl_Text_1 {
            get {
                return ResourceManager.GetString("PivotHelpControl_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you are done recording, add some detail about the issue, then tap below to email the log back to me and I will be in touch :.
        /// </summary>
        public static string PivotHelpControl_Text_2 {
            get {
                return ResourceManager.GetString("PivotHelpControl_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information gathering.
        /// </summary>
        public static string PivotHelpControl_Toggle_Header {
            get {
                return ResourceManager.GetString("PivotHelpControl_Toggle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the cache.
        /// </summary>
        public static string Settings_Button_DeleteCache {
            get {
                return ResourceManager.GetString("Settings_Button_DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Settings_Button_Logoff {
            get {
                return ResourceManager.GetString("Settings_Button_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this application.
        /// </summary>
        public static string Settings_Button_RateApp {
            get {
                return ResourceManager.GetString("Settings_Button_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files downloaded in this app..
        /// </summary>
        public static string Settings_Text_DeleteCache {
            get {
                return ResourceManager.GetString("Settings_Text_DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete login credentials stored in this app. This app doesn&apos;t store user/password, only the auth token..
        /// </summary>
        public static string Settings_Text_Logoff {
            get {
                return ResourceManager.GetString("Settings_Text_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string Settings_Text_RateApp {
            get {
                return ResourceManager.GetString("Settings_Text_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
